Traceback (most recent call last):
  File "/home/solgi/MSP-IMTS/tPatchGNN/run_models.py", line 101, in <module>
    data_obj = parse_datasets(args, patch_ts=True)
  File "/home/solgi/MSP-IMTS/lib/parse_datasets.py", line 290, in parse_datasets
    total_dataset = PersonActivity('../data/activity/', n_samples = args.n, download=True, device = device)
  File "/home/solgi/MSP-IMTS/lib/person_activity.py", line 64, in __init__
    self.download()
  File "/home/solgi/MSP-IMTS/lib/person_activity.py", line 84, in download
    os.makedirs(self.raw_folder, exist_ok=True)
  File "/home/solgi/miniconda3/envs/solgiland/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/solgi/miniconda3/envs/solgiland/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '../data/activity'
